appProjects:
    # Name will be used for the Argo CD AppProject and the Namespace the
    # applications will be deployed into
  - name: acm-policy

    # Description for the project
    description: "ACM policies for each OpenShift cluster"

    # Display name for the project
    displayName: "Baseline ACM Policies"

    # URL to a Git repo with application Helm charts for this project. This URL
    # should end in ".git"
    gitUrl: 'https://github.com/jayissi/Sandbox-ACM-Policy.git'

    # Git branch to pull charts from. Default: "main"
    gitBranch: main

    # Helm values file to use relative to each helm chart. Default: "values.yaml"
    valuesFile: values.yaml

    # List of applications to deploy into the project
    applications:
        # Name of the application. THIS MUST BE UNIQUE! Even if deployed into a
        # different project, Argo CD Application names must be unique
      - name: etcd-encryption

        # Path inside the project gitUrl to the Helm chart. Use "." if the
        # chart is in the root of the repo. Use a relative path otherwise
        gitPath: 'non-cluster-specific-acm-policies/etcd-encryption'

      - name: machineconfigpool
        gitPath: 'non-cluster-specific-acm-policies/machineconfigpool'
      - name: tls-v1.2-security-profile
        gitPath: 'non-cluster-specific-acm-policies/tls-v1.2-security-profile'
      - name: web-terminal
        gitPath: 'non-cluster-specific-acm-policies/web-terminal'
      - name: fips-check
        gitPath: 'non-cluster-specific-acm-policies/fips-check'
      - name: compliance-operator
        gitPath: 'non-cluster-specific-acm-policies/compliance-operator'
      - name: compliance-scan
        gitPath: 'non-cluster-specific-acm-policies/compliance-scan'
      - name: rhacs-operator
        gitPath: 'non-cluster-specific-acm-policies/rhacs-operator'
      - name: rhacs-secure-cluster
        gitPath: 'non-cluster-specific-acm-policies/rhacs-secure-cluster'
      - name: rook-ceph-operator-tolerations
        gitPath: 'non-cluster-specific-acm-policies/rook-ceph-operator-tolerations'
      - name: migrate-cluster-resources-to-infra-nodes
        gitPath: 'non-cluster-specific-acm-policies/migrate-cluster-resources-to-infra-nodes'
      - name: baseline-policy-set
        gitPath: 'non-cluster-specific-acm-policies/baseline-policy-set'

  # stackrox shared secrets
  - name: stackrox
    description: "Manage ACM Cluster share stackrox secure cluster secrets (e.g. $central_hostname, $central_port, sensor-tls, etc)"
    displayName: "Stackrox Shared Secrets"
    gitUrl: 'https://github.com/jayissi/Sandbox-ACM-Policy.git'
    gitBranch: main
    valuesFile: values.yaml
    applications:
      - name: shared-secure-cluster-secrets
        gitPath: 'managed-clusters/shared-secure-cluster-secrets'

  # hub-clusters configuration
  - name: hub-cluster-acm-policy
    description: "ACM policy configuration namespace solely for hub cluster"
    displayName: "hub-cluster ACM Policies"
    gitUrl: 'https://github.com/jayissi/Sandbox-ACM-Policy.git'
    gitBranch: main
    valuesFile: values.yaml
    applications:
      - name: rhacs-central
        gitPath: 'hub-cluster/rhacs-central'
      - name: rhacs-init-bundle
        gitPath: 'hub-cluster/rhacs-init-bundle'
      - name: hub-cluster-policy-set
        gitPath: 'hub-cluster/hub-cluster-policy-set'

  # local-cluster configuration
  - name: local-cluster-acm-policy
    description: "ACM policy configuration namespace specified for cluster 'local-cluster'"
    displayName: "local-cluster ACM Policies"
    gitUrl: 'https://github.com/jayissi/Sandbox-ACM-Policy.git'
    gitBranch: main
    valuesFile: local-cluster.values.yaml
    applications:
      - name: local-cluster-gp3-storageclass
        gitPath: 'cluster-specific-acm-policies/gp3-storageclass'
      - name: local-cluster-machine-sets
        gitPath: 'cluster-specific-acm-policies/machine-sets'
      - name: local-cluster-odf-deployment
        gitPath: 'cluster-specific-acm-policies/odf-deployment'
      - name: local-cluster-secret-store
        gitPath: 'cluster-specific-acm-policies/secret-store'
      - name: local-cluster-external-secrets
        gitPath: 'cluster-specific-acm-policies/external-secrets'
  #    - name: local-cluster-openshift-api-certificate
  #      gitPath: 'cluster-specific-acm-policies/certs/openshift-api-certificate'
  #    - name: local-cluster-openshift-ingress-certificate
  #      gitPath: 'cluster-specific-acm-policies/certs/openshift-ingress-certificate'
  #    - name: local-cluster-openshift-proxy-certificate
  #      gitPath: 'cluster-specific-acm-policies/certs/openshift-proxy-certificate'
      - name: local-cluster-acm-policy-set
        gitPath: 'cluster-specific-acm-policies/cluster-specific-policy-set'

  # managed-clusters configuration
  - name: managed-clusters-acm-policy
    description: "ACM policy configuration namespace specified for cluster(s) managed by RHACM"
    displayName: "managed-clusters ACM Policies"
    gitUrl: 'https://github.com/jayissi/Sandbox-ACM-Policy.git'
    gitBranch: main
    valuesFile: values.yaml
    applications:
      - name: ingresscontroller-hostname-share
        gitPath: 'managed-clusters/ingresscontroller-hostname-share'
      - name: managed-clusters-policy-set
        gitPath: 'managed-clusters/managed-clusters-policy-set'
